version: "3.8"

services:
  backend:
    image: jbonganciso04/note-app-backend:latest
    container_name: note-app-backend
    ports:
      - "8082:8082"
    networks:
      - app-network

  frontend:
    image: jbonganciso04/my-react-app:latest
    container_name: my-react-app
    ports:
      - "80:80"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
